// ---------------------------------------------------------------------------
// Contract Negotiation Protocol (CNP) types
// Reference: §7 & §8 of DSP 2025-1
// ---------------------------------------------------------------------------

import { DspContext } from "./common";
import { Offer, Permission, Prohibition, Duty } from "./catalog";

// ---------------------------------------------------------------------------
// States (§7.1.1)
// ---------------------------------------------------------------------------

/**
 * States of a Contract Negotiation, tracked by both parties in a ContractNegotiation entity.
 */
export enum NegotiationState {
	REQUESTED = "REQUESTED",
	OFFERED = "OFFERED",
	ACCEPTED = "ACCEPTED",
	AGREED = "AGREED",
	VERIFIED = "VERIFIED",
	FINALIZED = "FINALIZED",
	TERMINATED = "TERMINATED",
}

export const NEGOTIATION_TERMINAL_STATES: ReadonlySet<NegotiationState> =
	new Set([NegotiationState.FINALIZED, NegotiationState.TERMINATED]);

// ---------------------------------------------------------------------------
// Agreement (§7.2.3 / Appendix A)
// ---------------------------------------------------------------------------

/**
 * A concrete Policy associated with a specific Dataset that has been agreed
 * between the Provider and Consumer. It is a result of a ContractNegotiation
 * defining the Policy agreed to for a Dataset.
 */
export interface Agreement {
	"@id": string;
	"@type": "Agreement";
	/**
	 * Reference to the Asset (usually a Dataset) this agreement applies to.
	 *
	 * Note: although the Agreement has a target field, none of its Rules should
	 * have a target to prevent inconsistencies with the ODRL [inferencing rules
	 * for compact policies](https://www.w3.org/TR/odrl-model/#composition-compact)
	 */
	target: string;
	timestamp?: string;
	assigner: string;
	assignee: string;
	permission?: Permission[];
	prohibition?: Prohibition[];
	obligation?: Duty[];
	profile?: string | string[];
}

// ---------------------------------------------------------------------------
// ContractNegotiation - the entity tracked by both sides (§7.3.1)
// ---------------------------------------------------------------------------

/**
 * A set of interactions between a Provider and Consumer that establish an
 * Agreement. It is an instantiation of the state machine of a Contract
 * Negotiation Protocol. An outcome of a ContractNegotiation may be the
 * production of an Agreement.
 */
export interface ContractNegotiation {
	"@context"?: DspContext;
	"@type": "ContractNegotiation";
	providerPid: string;
	consumerPid: string;
	state: NegotiationState;
	agreement?: Agreement;
	/**
	 * The current offer in play. Set when the Consumer sends a
	 * ContractRequestMessage (Provider side) or when the Provider sends a
	 * ContractOfferMessage (Consumer side). Available to hooks so
	 * business logic can inspect terms without a separate store look-up.
	 */
	offer?: MessageOffer;
	/** Callback URL the other party sends messages to */
	callbackAddress?: string;
}

// ---------------------------------------------------------------------------
// Offer inside a message (must have target, §7.2.1 / §7.2.2)
// ---------------------------------------------------------------------------

export interface MessageOffer extends Omit<Offer, "target"> {
	/**
	 *
	 * MUST be set when offer appears inside a message (not a Catalog/Dataset)
	 */
	target: string;
}

// ---------------------------------------------------------------------------
// CNP messages (§7.2)
// ---------------------------------------------------------------------------

/**
 * Sent by a Consumer to initiate a Contract Negotiation or to respond to a
 * ContractOfferMessage sent by a Provider.
 *
 * §7.2.1 - sent by Consumer
 */
export interface ContractRequestMessage {
	"@context": DspContext;
	"@type": "ContractRequestMessage";
	/**
	 * A UUID generated by the Consumer to identify this negotiation.
	 */
	consumerPid: string;
	/**
	 * Required when joining an existing negotiation
	 */
	providerPid?: string;
	offer: MessageOffer;
	/**
	 * A URL indicating where messages to the Consumer should be sent in
	 * asynchronous settings. If the address is not understood, the Provider
	 * will respond with an unrecoverable error.
	 */
	callbackAddress: string;
}

/**
 * Sent by a Provider to initiate a Contract Negotiation or to respond to a
 * ContractRequestMessage sent by a Consumer.
 *
 * §7.2.2 - sent by Provider
 */
export interface ContractOfferMessage {
	"@context": DspContext;
	"@type": "ContractOfferMessage";
	providerPid: string;
	/** Required when joining an existing negotiation */
	consumerPid?: string;
	offer: MessageOffer;
	callbackAddress: string;
	dataset?: string;
}

/**
 * Sent by a Provider when it agrees to a Policy. It contains the
 * complete Agreement.
 *
 * §7.2.3 - sent by Provider
 */
export interface ContractAgreementMessage {
	"@context": DspContext;
	"@type": "ContractAgreementMessage";
	providerPid: string;
	consumerPid: string;
	agreement: Agreement;
}

/**
 * Sent by a Consumer to verify the acceptance of an Agreement.
 *
 * §7.2.4 - sent by Consumer
 */
export interface ContractAgreementVerificationMessage {
	"@context": DspContext;
	"@type": "ContractAgreementVerificationMessage";
	providerPid: string;
	consumerPid: string;
}

export type NegotiationEventType = "ACCEPTED" | "FINALIZED";

/**
 * When this message is sent by a Provider with an eventType property
 * set to "FINALIZED", an Agreement has been finalized and the
 * associated Dataset is accessible. The state machine is transitioned
 * to the FINALIZED state.
 *
 * §7.2.5 - sent by Consumer (ACCEPTED) or Provider (FINALIZED)
 */
export interface ContractNegotiationEventMessage {
	"@context": DspContext;
	"@type": "ContractNegotiationEventMessage";
	providerPid: string;
	consumerPid: string;
	eventType: NegotiationEventType;
}

/**
 * Sent by the Consumer or Provider indicating a cancellation
 * of the Contract Negotiation sequence. The message may be sent
 * at any state of a Contract Negotiation without providing an
 * explanation. Nevertheless, the sender may provide a description
 * to help the receiver.
 *
 * §7.2.6 - sent by either party
 */
export interface ContractNegotiationTerminationMessage {
	"@context": DspContext;
	"@type": "ContractNegotiationTerminationMessage";
	providerPid: string;
	consumerPid: string;
	code?: string;
	reason?: string[];
}

// ---------------------------------------------------------------------------
// CNP Error (§7.3.2)
// ---------------------------------------------------------------------------

/**
 * Object returned by the Consumer or Provider indicating an error
 * has occurred. It does not cause any state transition.
 */
export interface ContractNegotiationError {
	"@context": DspContext;
	"@type": "ContractNegotiationError";
	providerPid?: string;
	consumerPid?: string;
	code?: string;
	reason?: string[];
}
